apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pirulenc/pirulenc-iot.git
    targetRevision: HEAD
    path: confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  suncPolicy:
    automated:
      prune: true
      selfHeal: true
