Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.define "pjurdanaS" do |server|
        server.vm.hostname = "pjurdanaS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        server.vm.provision "shell", path: "scripts/install_server.sh"
    end
end