# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # First VM: pirulencS (Server)
  config.vm.define "pirulencS" do |server|
    server.vm.hostname = "pirulencS"
    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: "192.168.56.110", autostart: true
    
    server.vm.provider "libvirt" do |hv|
      hv.cpus = 1
      hv.memory = 1024
      hv.default_prefix = ""
      hv.mgmt_attach = false
    end
    
    server.vm.provision "file", source: "./Requirements", destination: "/tmp/manifests"
    server.vm.provision "shell", path: "./Scripts/script_server.sh"

  end

end