# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Disable vbguest auto-update
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  # First VM: pirulencS (Server)
  config.vm.define "pirulencS" do |server|
    server.vm.hostname = "pirulencS"
    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end
    
    server.vm.provision "file", source: "./Requirements", destination: "/tmp/manifests"
    server.vm.provision "shell", path: "./Scripts/script_server.sh"

  end

end