# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # First VM: pirulencS (Server)
  config.vm.define "pirulencS" do |server|
    server.vm.hostname = "pirulencS"
    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "libvirt" do |hv|
      hv.cpus = 1
      hv.memory = 1024
      hv.default_prefix = ""
    end

    server.vm.provision "shell", path: "./Scripts/script_server.sh"

  end

  # Second VM: pirulencSW (Worker)
  config.vm.define "pirulencSW" do |worker|
    worker.vm.hostname = "pirulencSW"
    worker.vm.box = "debian/bookworm64"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "libvirt" do |hv|
      hv.cpus = 1
      hv.memory = 1024
      hv.default_prefix = ""
    end

    worker.trigger.before :up do |trigger|
      trigger.info = "Waiting for pirulencS to be ready..."
      trigger.run = {inline: "bash -c 'until ping -c1 192.168.56.110 &>/dev/null; do sleep 1; done'"}
    end

    worker.vm.provision "shell", path: "./Scripts/script_serverworker.sh"

  end

end