# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # First VM: pirulencS (Server)
  config.vm.define "pirulencS" do |server|
    server.vm.hostname = "pirulencS"
    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "file", source: "Token_tmp", destination: "/tmp/Token"
    server.vm.provision "shell", path: "./Scripts/script_server.sh"

  end

  # Second VM: pirulencSW (Worker)
  config.vm.define "pirulencSW" do |worker|
    worker.vm.hostname = "pirulencSW"
    worker.vm.box = "debian/bookworm64"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    worker.vm.provision "file", source: "Token_tmp", destination: "/tmp/Token"
    worker.vm.provision "shell", path: "./Scripts/script_serverworker.sh"

  end

end